# Sentiment Analysis :TF-IDF

In [2]:
#importing libraries
import numpy as np
import re
import pickle
import nltk
from nltk.corpus import stopwords
from sklearn.datasets import load_files

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parijat\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
# importing datasets

In [5]:
reviews=load_files('txt_sentoken/')

In [6]:
x,y=reviews.data,reviews.target

In [7]:
y

array([1, 2, 2, ..., 2, 1, 1])

In [14]:
# Storing as Pickle Files
with open('x.pickle','wb') as f:
    pickle.dump(x,f)
    
with open('y.pickle','wb') as f:
    pickle.dump(y,f)

In [15]:
!ls

Text Classification.ipynb
txt_sentoken
x.pickle
y.pickle


In [81]:
# unpickling 
with open('x.pickle','rb') as f:
    x=pickle.load(f)
with open('y.pickle','rb') as f:
    y=pickle.load(f)

In [82]:
# creating the corpus
corpus=[]
for i in range(0,len(x)):
    review=re.sub(r'\W',' ',str(x[i]))
    review=review.lower()
    review=re.sub(r'\s+[a-z]\s+',' ',review)
    review=re.sub(r'^[a-z]\s+',' ',review)
    review=re.sub(r'\s+',' ',review)
    corpus.append(review)
    

In [83]:
#from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [84]:
vectorizer=TfidfVectorizer(max_features=2000,min_df=3,max_df=0.6,stop_words=stopwords.words('english'))

In [85]:
x=vectorizer.fit_transform(corpus).toarray()

In [86]:
# Pickling the classifier
with open('vect.pkl','wb') as f:
    pickle.dump(vectorizer,f)

In [44]:
x.shape

(2000, 2000)

In [45]:
x[0].shape

(2000,)

In [46]:
# from sklearn.feature_extraction.text import TfidfTransformer
# transformer=TfidfTransformer()
# x=transformer.fit_transform(x).toarray()

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)

In [54]:
train_x[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [55]:
train_y[0]

2

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
cls=LogisticRegression()

In [58]:
cls.fit(train_x,train_y)

LogisticRegression()

In [59]:
pred=cls.predict(test_x)

In [70]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [71]:
cm=confusion_matrix(test_y,pred)

In [72]:
cm

array([[168,  40],
       [ 21, 171]], dtype=int64)

In [77]:
print(f'{accuracy_score(test_y,pred)*100}%')

84.75%


In [75]:
print(classification_report(test_y,pred))

              precision    recall  f1-score   support

           1       0.89      0.81      0.85       208
           2       0.81      0.89      0.85       192

    accuracy                           0.85       400
   macro avg       0.85      0.85      0.85       400
weighted avg       0.85      0.85      0.85       400



In [90]:
# Pickling the classifier
with open('classifier.pkl','wb') as f:
    pickle.dump(cls,f)

In [92]:
#unpicklig the classifier and the vectorizer
with open('classifier.pkl','rb') as f:
    cls=pickle.load(f)

In [94]:
with open('vect.pkl','rb') as f:
    vect=pickle.load(f)

In [140]:
sample=['she has a bad temper']

In [141]:
sample=vect.transform(sample).toarray()

In [142]:
cls.predict(sample)[0]

1

In [1]:
# 1: bad, 2: good