In [68]:
import pandas as pd
import numpy as np
import pickle
import re
import nltk
import requests
#import stop-words
#import nltk
from nltk.corpus import stopwords

In [815]:
pwd

'C:\\Users\\Parijat\\Desktop\\sc2019'

In [816]:
data1=pd.read_csv('BASE_NS_CivicAddress_File_UT83.csv') # Residential

C:\Users\Parijat\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [817]:
data1.head(2)

SEGID                                       the_geom      Longz  \
0  17500026  POINT (-64.02346526630515 45.981042676909134) -64.023465   
1  17500027   POINT (-64.00823115601295 45.99031718310066) -64.008231   

        Long     Latz        Lat  CIVICNUM     PNTID CIVSUFFIX UNIT_NUM  \
0 -64.023465   45.981  45.981043      4053  17500314       NaN      NaN   
1 -64.008231  45.9903  45.990317      4399  17500135       NaN      NaN   

             ...            STRPREFIX      STRNAME STRSUFFIX STRDIR COMM_ID  \
0            ...                  NaN  Highway 366       NaN    NaN     175   
1            ...                  NaN  Highway 366       NaN    NaN     175   

                  COMM                MUN             COUNTY Type  \
0  Tidnish Cross Roads  Cumberland County  Cumberland County    0   
1  Tidnish Cross Roads  Cumberland County  Cumberland County    0   

                       Name  
0  yes residential housing   
1  yes residential housing   

[2 rows x 21 columns]

In [818]:
cols=['Name','Long','Lat','Type']

In [819]:
data=data1[cols]

In [820]:
data.head(2)

Name       Long        Lat  Type
0  yes residential housing  -64.023465  45.981043     0
1  yes residential housing  -64.008231  45.990317     0

In [821]:
data2=pd.read_csv('Day_Programs.csv') #Commercial

In [822]:
data2.head(2)

UID                          Name  \
0    1  Beehive Adult Service Centre   
1    2             Bonny Lea (SSCSA)   

                                             Address           Phone  \
0  1119 Station Street Aylesford, Nova Scotia B0P...  (902) 847-9696   
1                       5 Collicutt Rd, Windsor Road  (902) 275-5622   

              Fax                   Email  \
0  (902) 847-9189  beehiveasc@eastlink.ca   
1  (902) 275-2567  davidouthouse@sswap.ca   

                               Facebook                    Website  \
0  https://www.facebook.com/beehiveASC/  http://www.beehiveasc.ca/   
1                                   NaN                        NaN   

                               Hours       Long        Lat  \
0  8:00 am - 4:00 pm (M-F) (8-2 Sat) -64.838389  45.030217   
1                                NaN -64.270608  44.592503   

                        Location  Type  
0   (45.030217321, -64.83838879)     1  
1  (44.592502947, -64.270607962)     1

In [823]:
data2f=data2[cols]

In [824]:
len(data)

452819

In [825]:
len(data2f)

44

In [826]:
data=data.append(data2f)

In [827]:
len(data)

452863

In [828]:
data3=pd.read_csv('Hospitals.csv')#

In [829]:
data3.head(2)

Name            Address  \
0              Guysborough Memorial Hospital     10560 Route 16   
1  Buchanan Memorial Community Health Centre  32610 Cabot Trail   

             TOWN       COUNTY                     TYPE           Phone  \
0     Guysborough  Guysborough                Community  (902) 533-3702   
1  Neil's Harbour     Victoria  Community Health Centre  (902) 336-2200   

        Long        Lat               Location 1  Type  
0 -61.507135  45.402341  (45.402341, -61.507136)     1  
1 -60.334327  46.810570   (46.81057, -60.334327)     1

In [830]:
data=data.append(data3[cols])

In [831]:
data4=pd.read_csv('Nova_Scotia_Business_Inc._Export_Development_and_Investment_Attraction_Activity.csv')

In [832]:
data4.head(2)

Name                   nsbi_sector  \
0    Northern Business Intelligence  ICT (includes Digital Media)   
1  Fourth State Energy Incorporated                        Energy   

                      Deal Type  \
0  Business Development Program   
1  Business Development Program   

  NSBI Financial Contribution (Commitment/Announced) Place Name  \
0                                             10,850  Dartmouth   
1                                              3,750    Halifax   

                     nsbi_county PostalCode  fiscal year       Long  \
0  Halifax Regional Municipality     B3B1T4  2018 - 2019 -63.592360   
1  Halifax Regional Municipality     B3J2L4  2018 - 2019 -63.632286   

         Lat      New Georeferenced Column  Type  
0  44.706090    POINT (-63.59236 44.70609)     1  
1  44.654755  POINT (-63.632286 44.654755)     1

In [833]:
data=data.append(data4[cols])

In [834]:
data5=pd.read_csv('Public_Housing_Units_-_Nova_Scotia_Seniors.csv')

In [835]:
data5.head(2)

OBJECTID PROPERTY (Project Number)       PID               Namez  \
0       117                   330101X  65032708  Riverton Heights I   
1       324                   200214X  50067362            Bellevue   

                     Civic Address      Community Postal Code  \
0  19/27/29 Riverton Heights Drive  Pictou County     B0K 1S0   
1                   10 Grand Etang    Grand Etang     B0E 1L0   

   Number of Floors  Residential Units                     Housing Authority  \
0                 2                 20    Eastern Mainland Housing Authority   
1                 2                 15  Cape Breton Island Housing Authority   

                         ...                         OIL Heat ELECTRIC Heat  \
0                        ...                                Y             N   
1                        ...                                N             Y   

  Public WATER Well Water Public Sewer       Long        Lat  \
0            N          Y            Y -62.666417  45.543238   
1            N          Y            N -61.055994  46.537269   

                  Location  Type  \
0  (45.543238, -62.666417)     0   
1  (46.537269, -61.055994)     0   

                                                Name  
0  Riverton Heights IEastern Mainland Housing Aut...  
1       BellevueCape Breton Island Housing Authority  

[2 rows x 22 columns]

In [836]:
data=data.append(data5[cols])

In [837]:
data6=pd.read_csv('Register_of_Private_Career_Colleges.csv')

In [838]:
data6.head(2)

Date (yyyy-mm-dd)                    Name                   Program  \
0         12/9/2019  Academy of Cosmetology  Cosmetology-Hairdressing   
1         12/9/2019  Academy of Cosmetology                 Esthetics   

  Center Name    Street Address  Suite/Floor/Mailbox  City/Town Province  \
0         NaN  363 Windmill Road                 NaN  Dartmouth       NS   
1         NaN  363 Windmill Road                 NaN  Dartmouth       NS   

  Postal Code Mailing Address - PO Box/Street ...            Fax Toll Free  \
0     B3A 1J2                             NaN ...   902-461-4625       NaN   
1     B3A 1J2                             NaN ...   902-461-4625       NaN   

                                   Web                 Location       Longz  \
0  http://www.academyofcosmetology.com  (44.680924, -63.595946)  -63.595946   
1  http://www.academyofcosmetology.com  (44.680924, -63.595946)  -63.595946   

        Long   Latitude       Latz        Lat Type  
0 -63.595946  44.680924  44.680924  44.680924    1  
1 -63.595946  44.680924  44.680924  44.680924    1  

[2 rows x 29 columns]

In [839]:
data=data.append(data6[cols])

In [840]:
data7=pd.read_csv('Victim_Services_Offices.csv')

In [841]:
data=data.append(data7[cols])

In [842]:
data8=pd.read_csv('google_tags.csv')

In [843]:
data=data.append(data8[cols])

In [844]:
data.shape

(454271, 4)

In [845]:
data.head(2)

Name       Long        Lat  Type
0  yes residential housing  -64.023465  45.981043     0
1  yes residential housing  -64.008231  45.990317     0

In [846]:
datan=data[(data['Long'].isnull()==True) |(data['Lat'].isnull()==True) |(data['Type'].isnull()==True) ]

In [847]:
datan

Name  Long  Lat  Type
557              Influitive Corporation   NaN  NaN     1
566                         Columbus AI   NaN  NaN     1
744  Clearwater Fine Foods (Europe) Ltd   NaN  NaN     1
745  Clearwater Fine Foods (Europe) Ltd   NaN  NaN     1

In [848]:
l2=datan.index.tolist()

In [849]:
len(l2)

4

In [850]:
#data.drop(datan.index,inplace=True)
data.drop(l2,inplace=True)

In [851]:
datan=data[(data['Long'].isnull()==True) |(data['Lat'].isnull()==True) |(data['Type'].isnull()==True) ]

In [852]:
datan

Empty DataFrame
Columns: [Name, Long, Lat, Type]
Index: []

In [853]:
data.shape

(454263, 4)

In [854]:
data.head()

Name       Long        Lat  Type
0  yes residential housing  -64.023465  45.981043     0
1  yes residential housing  -64.008231  45.990317     0
2  yes residential housing  -64.005109  45.990115     0
3  yes residential housing  -64.003100  45.991033     0
4  yes residential housing  -64.003262  45.991681     0

In [855]:
data.dtypes

Name     object
Long    float64
Lat     float64
Type      int64
dtype: object

In [856]:
data.to_csv('clubbeddata.csv')

In [10]:
data=pd.read_csv('clubbeddata.csv')

In [23]:
data.head(4)

Unnamed: 0                      Name       Long        Lat  Type
0           0  yes residential housing  -64.023465  45.981043     0
1           1  yes residential housing  -64.008231  45.990317     0
2           2  yes residential housing  -64.005109  45.990115     0
3           3  yes residential housing  -64.003100  45.991033     0

In [2]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parijat\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [859]:
#breaks

In [860]:
for i in range(0, len(data)):
    #print(i)
    review = re.sub('[^a-zA-Z]', ' ', data.iloc[i,0])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [861]:
with open('corpus.pkl','wb') as f:
    pickle.dump(corpus,f)

In [12]:
with open('corpus.pkl','rb') as f:
    corpus=pickle.load(f)

In [4]:
#l=[x for x in corpus if x!='premis build hous']

In [5]:
#l

In [6]:
len(corpus)

454263

In [7]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1380)
#cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
y = data.iloc[:, 4].values

NameError: name 'data' is not defined

In [13]:
#y = data.iloc[:, 4].values

In [25]:
with open('cv.pkl', 'wb') as f:
    pickle.dump(cv, f)

In [26]:
x.shape

(454263, 1380)

In [27]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [85]:
x.shape

(454263, 1380)

In [28]:
y.shape

(454263,)

In [29]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [86]:
y.shape

(454263,)

In [ ]:
#data['Long']=data['Long'].astype(float)

In [ ]:
breaks

In [ ]:
#x=np.array(data[['Long','Lat']])

In [ ]:
#x

In [ ]:
#y=np.ravel(data[['Type']])

In [ ]:
#y

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

NameError: name 'x' is not defined

In [31]:
with open('x_train.pkl', 'wb') as f:
    pickle.dump(x_train, f)

In [87]:
x_train.shape

(363410, 1380)

In [88]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
with open('x_test.pkl', 'wb') as f:
    pickle.dump(x_test, f)

In [19]:
x_test.dtype

dtype('int64')

In [33]:
with open('y_train.pkl', 'wb') as f:
    pickle.dump(y_train, f)

In [34]:
with open('y_test.pkl', 'wb') as f:
    pickle.dump(y_test, f)

In [26]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    return diagonal_sum / sum_of_all_elements 

In [36]:
# Naive Bayes Classifier------------------------>>>
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('NB Accuracy:',accuracy(cm)*100,'%')

# saving the DT model 
filename = 'NB_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

NB Accuracy: 100.0 %


In [95]:
#classifier.shape()

AttributeError: 'GaussianNB' object has no attribute 'shape'

In [96]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('RF Accuracy:',accuracy(cm)*100,'%')

RF Accuracy: 100.0 %


In [97]:
# saving the DT model 
filename = 'RF_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [5]:
with open('x_train.pkl','rb') as f:
    x_train=pickle.load(f)

In [20]:
x_train.dtype

dtype('int64')

In [6]:
with open('y_train.pkl','rb') as f:
    y_train=pickle.load(f)   

In [21]:
y_train.dtype

dtype('int64')

In [7]:
with open('x_test.pkl','rb') as f:
    x_test=pickle.load(f)  

In [22]:
x_test.dtype

dtype('int64')

In [8]:
with open('y_test.pkl','rb') as f:
    y_test=pickle.load(f) 

In [23]:
y_test.dtype

dtype('int64')

In [24]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(x_train, y_train) 

# Predicting the Test set results
y_pred = classifier.predict(x_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('SVM Accuracy:',accuracy(cm)*100,'%')

NameError: name 'accuracy' is not defined

In [27]:
print('SVM Accuracy:',accuracy(cm)*100,'%')

SVM Accuracy: 100.0 %


In [28]:
# saving the DT model 
filename = 'SVM_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [37]:
engine_nb = pickle.load(open('NB_model.sav', 'rb'))
#result = cls_engine.score(x_test, y_test)
#print(result)

In [150]:
engine_rf = pickle.load(open('RF_model.sav', 'rb'))
#result = cls_engine.score(x_test, y_test)
#print(result)

In [29]:
engine_svm = pickle.load(open('SVM_model.sav', 'rb'))
#result = cls_engine.score(x_test, y_test)
#print(result)

# Application

In [204]:
with open('apikey.txt') as f:
    api_key = f.readline()
    f.close

In [232]:
address= input('Type an adress:')

Type an adress:41 Brundage Lane


In [233]:
address_raw=address
adrs=re.sub('[^a-zA-Z0-9]', '', address)
adrs

'41BrundageLane'

In [234]:
address=address+',NS,Canada'
address

'41 Brundage Lane,NS,Canada'

In [235]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="XX")
location = geolocator.geocode(address)
#print(location)
aa=location.raw
aa

{'place_id': 15019411,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
 'osm_type': 'way',
 'osm_id': 241058475,
 'boundingbox': ['45.990354333307',
  '45.990454333307',
  '-63.980848733151',
  '-63.980748733151'],
 'lat': '45.990404333307',
 'lon': '-63.9807987331509',
 'display_name': '41, Brundage Lane, Tidnish Cross Road, Municipality of the County of Cumberland, Cumberland County, Nova Scotia, B4H 3X9, Canada',
 'class': 'place',
 'type': 'house',
 'importance': 0.42099999999999993}

In [246]:
if aa!=None:
    print('hello')

hello


In [247]:
type(None)

NoneType

In [239]:
latt=aa['lat']
latt

'45.990404333307'

In [242]:
longg=aa['lon']
type(longg)

str

In [245]:
longg=float(longg)

In [226]:
a1=aa['display_name']
a2=aa['class']
a3=aa['type']

a1,a2,a3

('Bank of Montreal Building, 5151, George Street, Downtown Halifax, Halifax, Halifax Regional Municipality, Halifax County, Nova Scotia, B3J 2P8, Canada',
 'building',
 'yes')

In [227]:
address=a1
a12=address.split(', ')
a12

['Bank of Montreal Building',
 '5151',
 'George Street',
 'Downtown Halifax',
 'Halifax',
 'Halifax Regional Municipality',
 'Halifax County',
 'Nova Scotia',
 'B3J 2P8',
 'Canada']

In [228]:
adrs2=a12[0]+''+a12[1]
adrs2=re.sub('[^a-zA-Z0-9]', '', adrs2)
adrs2

'BankofMontrealBuilding5151'

In [229]:
if adrs==adrs2:
    address=address_raw
else:    
    address=''
    n=2
    for i in range(n):
        if i!=n-1:
            address+=a12[i]+','
        else:
            address+=a12[i] 
address

'Bank of Montreal Building,5151'

In [230]:
address=address+',Halifax,Canada'
address

'Bank of Montreal Building,5151,Halifax,Canada'

In [231]:
URL3='https://maps.googleapis.com/maps/api/place/findplacefromtext/json?fields=photos,formatted_address,name,types,geometry,place_id'
inputtype='textquery'
PARAMS3 = {'input':address,'inputtype':inputtype,'key':api_key}
r3 = requests.get(url = URL3, params = PARAMS3)
r3
data33=r3.json()
data33


{'candidates': [{'formatted_address': '1695 Grafton St, Halifax, NS B3J 0E7, Canada',
   'geometry': {'location': {'lat': 44.6460845, 'lng': -63.5749315},
    'viewport': {'northeast': {'lat': 44.64743522989272,
      'lng': -63.57357817010728},
     'southwest': {'lat': 44.64473557010727, 'lng': -63.57627782989272}}},
   'name': 'BMO Bank of Montreal',
   'photos': [{'height': 4048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107762529086617450118/photos">John Hayne</a>'],
     'photo_reference': 'CmRaAAAAhOcz0KeNWplvn1TuSfCtgz2Hj1Stb2jRNBmk527Hvf1N9s8IUMV53_lu9uHnqOISS67fgH1ulX3Ek0J0LYVWPV5x2n2rAWxPr8WMN5nXrqpIe86oknnDZ-mpom0MrPISEhAoEftUUmk_DSzyB4oGHcLCGhSYuEfQRzpw9BA0ZKv_1UzxGI3EDw',
     'width': 3036}],
   'place_id': 'ChIJFZ3xrc0jWksRCOKeGGYNBOI',
   'types': ['bank', 'atm', 'finance', 'point_of_interest', 'establishment']},
  {'formatted_address': '5151 George St, Halifax, NS B3J 1M5, Canada',
   'geometry': {'location': {'lat': 44.6487608, 'lng': 

name=''
for i in range (len(data33['candidates'][0]['name'])):
    if i!=len(data33['candidates'][0]['name'])-1:
        name+=data33['candidates'][0]['name'][i]+','
    else:
        name+=data33['candidates'][0]['name'][i]
name

In [147]:
name=data33['candidates'][0]['name']
name

'6362 Pepperell St'

In [148]:
xalien=''
if a2!='building':
    xalien=name+' '+a2+' '+a3
elif a2=='building':
    if 'premise'in data33['candidates'][0]['types']:
        xalien=name+' '+a3
    else:
        xalien=name+' '
        for i in range(len(data33['candidates'][0]['types'])):
            if i!=len(data33['candidates'][0]['types'])-1:                   
                   xalien+=data33['candidates'][0]['types'][i]+' '
            else:
                   xalien+=data33['candidates'][0]['types'][i]
                   
    
xalien


'6362 Pepperell St yes'

In [149]:
#review=xalien

In [150]:
with open('corpus.pkl','rb') as f:
    corpus_alien=pickle.load(f)

In [151]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Parijat\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [152]:
review = re.sub('[^a-zA-Z]', ' ', xalien)
review = review.lower()
review = review.split()
ps = PorterStemmer()
review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
review = ' '.join(review)
corpus_alien.append(review)

In [153]:
#corpus_alien[-1]

with open('cv.pkl', 'rb') as f:
    cv=pickle.load(f)

In [154]:
from sklearn.feature_extraction.text import CountVectorizer

In [155]:
cv = CountVectorizer(max_features = 1380)

In [156]:
xalien= cv.fit_transform(corpus_alien).toarray()

In [157]:
x_alien=xalien[[-1]]

In [158]:
x_alien.shape

(1, 1380)

In [159]:
x_alien

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [160]:
with open('NB_model.sav', 'rb') as f:
    engine_nb = pickle.load(f)

In [161]:
yalien_NB=engine_nb.predict(x_alien)
yalien_NB

array([1], dtype=int64)

In [162]:
with open('RF_model.sav', 'rb') as f:
    engine_rf = pickle.load(f)

In [163]:
yalien_RF=engine_rf.predict(x_alien)
yalien_RF

array([1], dtype=int64)

In [164]:
yalien_SVM=engine_svm.predict(x_alien)
yalien_SVM

array([1], dtype=int64)

In [165]:
#yalien_SVM=0

In [166]:
def most_frequent(List): 
    return max(set(List), key = List.count) 

In [167]:
yalien_list=[yalien_NB[0],yalien_RF[0],yalien_SVM[0]]

In [168]:
yalien=most_frequent(yalien_list)
yalien

1

In [169]:
prediction=''
if yalien==0:
    prediction='Residential Property'
elif yalien==1:
    prediction='Commercial Property'
    
prediction
    

'Commercial Property'

In [67]:
    if data33['status']=='OK':
        # extracting latitude, longitude and formatted address 
        # of the first matching location 
        latitude = data33['candidates'][0]['geometry']['location']['lat'] 
        longitude = data33['candidates'][0]['geometry']['location']['lng'] 
        
    else:
        print('Enter Corrct Address')

In [165]:
latitude, longitude

(44.6487608, -63.57308159999999)